version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /

    # Group packages into shared PR
    groups:
      build:
        patterns:
          - '@babel/*'
          - 'autoprefixer'
          - 'cssnano'
          - 'cssnano-*'
          - 'nunjucks'
          - 'postcss'
          - 'postcss-*'
          - 'sass-embedded'

      lint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint'
          - 'eslint-*'
          - 'html-validate'
          - 'prettier'
          - 'stylelint'
          - 'stylelint-*'
          - 'typescript'

      test:
        patterns:
          - '@testing-library/*'
          - 'babel-jest'
          - 'backstopjs'
          - 'jest'
          - 'jest-*'
          - 'outdent'
          - 'playwright'
          - 'playwright-*'
          - 'puppeteer'
          - 'puppeteer-*'

      tools:
        patterns:
          - 'concurrently'
          - 'del-cli'
          - 'gulp'
          - 'gulp-*'
          - 'wait-on'

    schedule:
      interval: monthly

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

      # Include indirect browser data updates
      # https://caniuse.com
      - dependency-name: caniuse-lite

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directories:
      - .github/workflows/
      - .github/workflows/actions/build/
      - .github/workflows/actions/diff/

    schedule:
      interval: 'monthly'
