language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - ~/.npm
    - ~/.cache
services:
  - docker
stages:
  - tests
  - name: master
    if: branch = master
  - name: tag
    if: tag IS present

jobs:
  include:
    - stage: tests
      name: Linting
      script: npm run lint

    - stage: tests
      name: Backstop
      before_script:
        - npm start &
      script:
        # Usually the `backstop test --docker` command would be used to run the tests,
        # but in travis we need to add a --network="host" flag to the docker-run command
        # so we compose our own docker-run command.
        - docker run --rm -it --network="host" --mount type=bind,source="/home/travis/build/nhsuk/nhsuk-frontend",target=/src backstopjs/backstopjs:latest test --config=tests/backstop/backstop.js --moby --testhost=http://127.0.0.1:3000

    - stage: master
      name: github pages
      script: npm run build-gh-pages
      deploy:
        provider: pages
        local-dir: ./dist/app
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true

    - stage: tag
      name: publish to git releases
      script: npm run build-gh-release
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: ./dist/nhsuk-frontend-*.zip
        skip_cleanup: true
        on:
          tags: true

    - stage: tag
      name: publish to npm
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        on:
          tags: true
        skip_cleanup: true


notifications:
  slack: nhsuk:$SLACK_TOKEN#frontend
