language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - ~/.npm
    - ~/.cache
stages:
  - tests
  - name: master
    if: branch = master
  - name: tag
    if: tag IS present

jobs:
  include:
    - stage: tests
      script: npm test

    - stage: deploy
      name: github pages
      script: npm run build-gh-pages
      deploy:
        provider: pages
        local-dir: ./dist/docs
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master

    - stage: deploy
      name: publish to git releases
      script: npm run build-gh-release
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: ./dist/nhsuk-frontend-*.zip
        skip_cleanup: true
        on:
          tags: true
notifications:
  slack: nhsuk:$SLACK_TOKEN#frontend
